// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Defines an Analyzer.
///
/// An analyzer processes data from its input streams using the logic defined in
/// the Operator that it represents. Of course, it produces data for the output
/// streams declared in the Operator.
public struct AnalyzerDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of this analyzer.
  ///
  /// Tentatively [a-z][a-z0-9]*(_[a-z0-9]+)*.
  public var analyzer: Swift.String = Swift.String()

  /// The name of the operator that this analyzer runs.
  ///
  /// Must match the name of a supported operator.
  public var `operator`: Swift.String = Swift.String()

  /// Input streams.
  public var inputs: [AnalyzerDefinition.StreamInput] = []

  /// The attribute values that this analyzer applies to the operator.
  ///
  /// Supply a mapping between the attribute names and the actual value you wish
  /// to apply. If an attribute name is omitted, then it will take a
  /// preconfigured default value.
  public var attrs: [Swift.String: AttributeValue] = [:]

  /// Debug options.
  public var debugOptions: AnalyzerDefinition.DebugOptions? = nil

  /// Operator option.
  public var operatorOption: AnalyzerDefinition.OperatorOption? = nil

  /// Initialize a new instance of `AnalyzerDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzerDefinition().with { $0.analyzer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case analyzer = "analyzer"
    case `operator` = "operator"
    case inputs = "inputs"
    case attrs = "attrs"
    case debugOptions = "debugOptions"
    case operatorOption = "operatorOption"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.analyzer = try container.decode(Swift.String.self, forKey: .analyzer)
    self.`operator` = try container.decode(Swift.String.self, forKey: .`operator`)
    self.inputs = try container.decode([AnalyzerDefinition.StreamInput].self, forKey: .inputs)
    self.attrs = try container.decode([Swift.String: AttributeValue].self, forKey: .attrs)
    self.debugOptions = try container.decodeIfPresent(
      AnalyzerDefinition.DebugOptions.self, forKey: .debugOptions)
    self.operatorOption = try container.decodeIfPresent(
      AnalyzerDefinition.OperatorOption.self, forKey: .operatorOption)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.analyzer, forKey: .analyzer)
    try container.encode(self.`operator`, forKey: .`operator`)
    try container.encode(self.inputs, forKey: .inputs)
    try container.encode(self.attrs, forKey: .attrs)
    try container.encode(self.debugOptions, forKey: .debugOptions)
    try container.encode(self.operatorOption, forKey: .operatorOption)
  }

  /// The inputs to this analyzer.
  ///
  /// We accept input name references of the following form:
  /// <analyzer-name>:<output-argument-name>
  ///
  /// Example:
  ///
  /// Suppose you had an operator named "SomeOp" that has 2 output
  /// arguments, the first of which is named "foo" and the second of which is
  /// named "bar", and an operator named "MyOp" that accepts 2 inputs.
  ///
  /// Also suppose that there is an analyzer named "some-analyzer" that is
  /// running "SomeOp" and another analyzer named "my-analyzer" running "MyOp".
  ///
  /// To indicate that "my-analyzer" is to consume "some-analyzer"'s "foo"
  /// output as its first input and "some-analyzer"'s "bar" output as its
  /// second input, you can set this field to the following:
  /// input = ["some-analyzer:foo", "some-analyzer:bar"]
  public struct StreamInput: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the stream input (as discussed above).
    public var input: Swift.String = Swift.String()

    /// Initialize a new instance of `StreamInput`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamInput().with { $0.input = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.StreamInput"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Options available for debugging purposes only.
  public struct DebugOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Environment variables.
    public var environmentVariables: [Swift.String: Swift.String] = [:]

    /// Initialize a new instance of `DebugOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DebugOptions().with { $0.environmentVariables = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.DebugOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Option related to the operator.
  public struct OperatorOption: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Tag of the operator.
    public var tag: Swift.String = Swift.String()

    /// Registry of the operator. e.g. public, dev.
    public var registry: Swift.String = Swift.String()

    /// Initialize a new instance of `OperatorOption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OperatorOption().with { $0.tag = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.OperatorOption"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
