// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Stores the criteria-annotation matching results for each search result item.
public struct AnnotationMatchingResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The criteria used for matching. It can be an input search criteria or a
  /// criteria converted from a facet selection.
  public var criteria: Criteria? = nil

  /// Matched annotations for the criteria.
  public var matchedAnnotations: [Annotation] = []

  /// Status of the match result. Possible values:
  /// FAILED_PRECONDITION - the criteria is not eligible for match.
  /// OK - matching is performed.
  public var status: GoogleRpc.Status? = nil

  /// Initialize a new instance of `AnnotationMatchingResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotationMatchingResult().with { $0.criteria = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AnnotationMatchingResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
