// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing Application object
public struct Application: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create timestamp
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. [Output only] Update timestamp
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. A user friendly display name for the solution.
  public var displayName: Swift.String = Swift.String()

  /// A description for this application.
  public var description: Swift.String = Swift.String()

  /// Application graph configuration.
  public var applicationConfigs: ApplicationConfigs? = nil

  /// Output only. Application graph runtime info. Only exists when application
  /// state equals to DEPLOYED.
  public var runtimeInfo: Application.ApplicationRuntimeInfo? = nil

  /// Output only. State of the application.
  public var state: Application.State = Application.State()

  /// Billing mode of the application.
  public var billingMode: Application.BillingMode = Application.BillingMode()

  /// Initialize a new instance of `Application`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Application().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Message storing the runtime information of the application.
  public struct ApplicationRuntimeInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Timestamp when the engine be deployed
    public var deployTime: GoogleCloudWKT.Timestamp? = nil

    /// Globally created resources like warehouse dataschemas.
    public var globalOutputResources: [Application.ApplicationRuntimeInfo.GlobalOutputResource] = []

    /// Monitoring-related configuration for this application.
    public var monitoringConfig: Application.ApplicationRuntimeInfo.MonitoringConfig? = nil

    /// Initialize a new instance of `ApplicationRuntimeInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ApplicationRuntimeInfo().with { $0.deployTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Message about output resources from application.
    public struct GlobalOutputResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The full resource name of the outputted resources.
      public var outputResource: Swift.String = Swift.String()

      /// The name of graph node who produces the output resource name.
      /// For example:
      /// output_resource:
      /// /projects/123/locations/us-central1/corpora/my-corpus/dataSchemas/my-schema
      /// producer_node: occupancy-count
      public var producerNode: Swift.String = Swift.String()

      /// The key of the output resource, it has to be unique within the same
      /// producer node. One producer node can output several output resources,
      /// the key can be used to match corresponding output resources.
      public var key: Swift.String = Swift.String()

      /// Initialize a new instance of `GlobalOutputResource`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GlobalOutputResource().with { $0.outputResource = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.Application.ApplicationRuntimeInfo.GlobalOutputResource"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Monitoring-related configuration for an application.
    public struct MonitoringConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Whether this application has monitoring enabled.
      public var enabled: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `MonitoringConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MonitoringConfig().with { $0.enabled = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.Application.ApplicationRuntimeInfo.MonitoringConfig"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Application.ApplicationRuntimeInfo"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// State of the Application
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// State CREATED.
    case created
    /// State DEPLOYING.
    case deploying
    /// State DEPLOYED.
    case deployed
    /// State UNDEPLOYING.
    case undeploying
    /// State DELETED.
    case deleted
    /// State ERROR.
    case error
    /// State CREATING.
    case creating
    /// State Updating.
    case updating
    /// State Deleting.
    case deleting
    /// State Fixing.
    case fixing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .created: return 1
      case .deploying: return 2
      case .deployed: return 3
      case .undeploying: return 4
      case .deleted: return 5
      case .error: return 6
      case .creating: return 7
      case .updating: return 8
      case .deleting: return 9
      case .fixing: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .created: return "CREATED"
      case .deploying: return "DEPLOYING"
      case .deployed: return "DEPLOYED"
      case .undeploying: return "UNDEPLOYING"
      case .deleted: return "DELETED"
      case .error: return "ERROR"
      case .creating: return "CREATING"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .fixing: return "FIXING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATED": self = .created
      case "DEPLOYING": self = .deploying
      case "DEPLOYED": self = .deployed
      case "UNDEPLOYING": self = .undeploying
      case "DELETED": self = .deleted
      case "ERROR": self = .error
      case "CREATING": self = .creating
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "FIXING": self = .fixing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .created
      case 2: self = .deploying
      case 3: self = .deployed
      case 4: self = .undeploying
      case 5: self = .deleted
      case 6: self = .error
      case 7: self = .creating
      case 8: self = .updating
      case 9: self = .deleting
      case 10: self = .fixing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .created: return try container.encode(1)
      case .deploying: return try container.encode(2)
      case .deployed: return try container.encode(3)
      case .undeploying: return try container.encode(4)
      case .deleted: return try container.encode(5)
      case .error: return try container.encode(6)
      case .creating: return try container.encode(7)
      case .updating: return try container.encode(8)
      case .deleting: return try container.encode(9)
      case .fixing: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Billing mode of the Application
  public enum BillingMode: Codable, Equatable, Sendable {
    /// The default value.
    case unspecified
    /// Pay as you go billing mode.
    case payg
    /// Monthly billing mode.
    case monthly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .payg: return 1
      case .monthly: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BILLING_MODE_UNSPECIFIED"
      case .payg: return "PAYG"
      case .monthly: return "MONTHLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BillingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BILLING_MODE_UNSPECIFIED": self = .unspecified
      case "PAYG": self = .payg
      case "MONTHLY": self = .monthly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BillingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .payg
      case 2: self = .monthly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .payg: return try container.encode(1)
      case .monthly: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Application"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
