// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message of the response from customer's Cloud Function to AppPlatform.
public struct AppPlatformCloudFunctionResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The modified annotations that is returned back to AppPlatform.
  /// If the annotations fields are empty, then those annotations will be dropped
  /// by AppPlatform.
  public var annotations: [AppPlatformCloudFunctionResponse.StructedOutputAnnotation] = []

  /// If set to true, AppPlatform will use original annotations instead of
  /// dropping them, even if it is empty in the annotations filed.
  public var annotationPassthrough: Swift.Bool = Swift.Bool()

  /// The event notifications that is returned back to AppPlatform. Typically it
  /// will then be configured to be consumed/forwared to a operator that handles
  /// events, such as Pub/Sub operator.
  public var events: [AppPlatformEventBody] = []

  /// Initialize a new instance of `AppPlatformCloudFunctionResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppPlatformCloudFunctionResponse().with { $0.annotations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A general annotation message that uses struct format to represent different
  /// concrete annotation protobufs.
  public struct StructedOutputAnnotation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The struct format of the actual annotation.
    public var annotation: GoogleCloudWKT.Struct? = nil

    /// Initialize a new instance of `StructedOutputAnnotation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StructedOutputAnnotation().with { $0.annotation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionResponse.StructedOutputAnnotation"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
