// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message of content of appPlatform event
public struct AppPlatformEventBody: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Human readable string of the event like "There are more than 6 people in
  /// the scene". or "Shelf is empty!".
  public var eventMessage: Swift.String = Swift.String()

  /// For the case of Pub/Sub, it will be stored in the message attributes.
  /// ​​pubsub.proto
  public var payload: GoogleCloudWkt.Struct? = nil

  /// User defined Event Id, used to classify event, within a delivery interval,
  /// events from the same application instance with the same id will be
  /// de-duplicated & only first one will be sent out. Empty event_id will be
  /// treated as "".
  public var eventId: Swift.String = Swift.String()

  /// Initialize a new instance of `AppPlatformEventBody`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppPlatformEventBody().with { $0.eventMessage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AppPlatformEventBody"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
