// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class AppPlatformRetry: AppPlatformStub {
    let inner: any AppPlatformStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any AppPlatformStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listApplications(
      request: ListApplicationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListApplicationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApplicationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListApplicationsResponse
          in
          return try await self.inner.listApplications(request: r, options: o)
        })
    }

    public func getApplication(
      request: GetApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Application {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Application
          in
          return try await self.inner.getApplication(request: r, options: o)
        })
    }

    public func createApplication(
      request: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createApplication(request: r, options: o)
        })
    }

    public func updateApplication(
      request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApplication(request: r, options: o)
        })
    }

    public func deleteApplication(
      request: DeleteApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteApplication(request: r, options: o)
        })
    }

    public func deployApplication(
      request: DeployApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeployApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deployApplication(request: r, options: o)
        })
    }

    public func undeployApplication(
      request: UndeployApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UndeployApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeployApplication(request: r, options: o)
        })
    }

    public func addApplicationStreamInput(
      request: AddApplicationStreamInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AddApplicationStreamInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.addApplicationStreamInput(request: r, options: o)
        })
    }

    public func removeApplicationStreamInput(
      request: RemoveApplicationStreamInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RemoveApplicationStreamInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.removeApplicationStreamInput(request: r, options: o)
        })
    }

    public func updateApplicationStreamInput(
      request: UpdateApplicationStreamInputRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApplicationStreamInputRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApplicationStreamInput(request: r, options: o)
        })
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createApplicationInstances(
      request: CreateApplicationInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApplicationInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createApplicationInstances(request: r, options: o)
        })
    }

    public func deleteApplicationInstances(
      request: DeleteApplicationInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteApplicationInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteApplicationInstances(request: r, options: o)
        })
    }

    public func updateApplicationInstances(
      request: UpdateApplicationInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApplicationInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApplicationInstances(request: r, options: o)
        })
    }

    public func listDrafts(
      request: ListDraftsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListDraftsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDraftsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListDraftsResponse
          in
          return try await self.inner.listDrafts(request: r, options: o)
        })
    }

    public func getDraft(
      request: GetDraftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Draft {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDraftRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Draft
          in
          return try await self.inner.getDraft(request: r, options: o)
        })
    }

    public func createDraft(
      request: CreateDraftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDraftRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDraft(request: r, options: o)
        })
    }

    public func updateDraft(
      request: UpdateDraftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDraftRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDraft(request: r, options: o)
        })
    }

    public func deleteDraft(
      request: DeleteDraftRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDraftRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDraft(request: r, options: o)
        })
    }

    public func listProcessors(
      request: ListProcessorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListProcessorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListProcessorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListProcessorsResponse
          in
          return try await self.inner.listProcessors(request: r, options: o)
        })
    }

    public func listPrebuiltProcessors(
      request: ListPrebuiltProcessorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListPrebuiltProcessorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ListPrebuiltProcessorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListPrebuiltProcessorsResponse
          in
          return try await self.inner.listPrebuiltProcessors(request: r, options: o)
        })
    }

    public func getProcessor(
      request: GetProcessorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Processor {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetProcessorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Processor
          in
          return try await self.inner.getProcessor(request: r, options: o)
        })
    }

    public func createProcessor(
      request: CreateProcessorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateProcessorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createProcessor(request: r, options: o)
        })
    }

    public func updateProcessor(
      request: UpdateProcessorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateProcessorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateProcessor(request: r, options: o)
        })
    }

    public func deleteProcessor(
      request: DeleteProcessorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteProcessorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteProcessor(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
