// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The source of the asset.
public struct AssetSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var sourceForm: OneOf_SourceForm? = nil

  /// Initialize a new instance of `AssetSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AssetSource().with { $0.assetGcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case assetGcsSource = "assetGcsSource"
    case assetContentData = "assetContentData"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var sourceForm: OneOf_SourceForm? = nil
    let sourceFormCheckAndSet = {
      if sourceForm != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceForm'"))
      }
      sourceForm = $0
    }
    if let assetGcsSource = try container.decodeIfPresent(
      AssetSource.AssetGcsSource?.self, forKey: .assetGcsSource)
    {
      try sourceFormCheckAndSet(.assetGcsSource(assetGcsSource))
    }
    if let assetContentData = try container.decodeIfPresent(
      AssetSource.AssetContentData?.self, forKey: .assetContentData)
    {
      try sourceFormCheckAndSet(.assetContentData(assetContentData))
    }
    self.sourceForm = sourceForm
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.sourceForm {
      switch choice {
      case .assetGcsSource(let value):
        try container.encode(value, forKey: .assetGcsSource)
      case .assetContentData(let value):
        try container.encode(value, forKey: .assetContentData)
      }
    }
  }

  /// The asset source is from Cloud Storage.
  public struct AssetGcsSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Cloud storage uri.
    public var gcsUri: Swift.String = Swift.String()

    /// Initialize a new instance of `AssetGcsSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AssetGcsSource().with { $0.gcsUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AssetSource.AssetGcsSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The content of the asset.
  public struct AssetContentData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var assetContentData: Foundation.Data = Foundation.Data()

    /// Initialize a new instance of `AssetContentData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AssetContentData().with { $0.assetContentData = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AssetSource.AssetContentData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_SourceForm: Codable, Equatable, Sendable {
    /// The source of the asset is from Cloud Storage.
    indirect case assetGcsSource(AssetSource.AssetGcsSource?)
    /// The source of the asset is from content bytes.
    indirect case assetContentData(AssetSource.AssetContentData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AssetSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
