// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents an actual value of an operator attribute.
public struct AttributeValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Attribute value.
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `AttributeValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttributeValue().with { $0.i = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case i = "i"
    case f = "f"
    case b = "b"
    case s = "s"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let i = try container.decodeIfPresent(Swift.Int64.self, forKey: .i) {
      try valueCheckAndSet(.i(i))
    }
    if let f = try container.decodeIfPresent(Swift.Float.self, forKey: .f) {
      try valueCheckAndSet(.f(f))
    }
    if let b = try container.decodeIfPresent(Swift.Bool.self, forKey: .b) {
      try valueCheckAndSet(.b(b))
    }
    if let s = try container.decodeIfPresent(Foundation.Data.self, forKey: .s) {
      try valueCheckAndSet(.s(s))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.value {
      switch choice {
      case .i(let value):
        try container.encode(value, forKey: .i)
      case .f(let value):
        try container.encode(value, forKey: .f)
      case .b(let value):
        try container.encode(value, forKey: .b)
      case .s(let value):
        try container.encode(value, forKey: .s)
      }
    }
  }

  /// Attribute value.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// int.
    case i(Swift.Int64)
    /// float.
    case f(Swift.Float)
    /// bool.
    case b(Swift.Bool)
    /// string.
    case s(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AttributeValue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
