// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Prediction output format for Image and Text Classification.
public struct ClassificationPredictionResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource IDs of the AnnotationSpecs that had been identified.
  public var ids: [Swift.Int64] = []

  /// The display names of the AnnotationSpecs that had been identified, order
  /// matches the IDs.
  public var displayNames: [Swift.String] = []

  /// The Model's confidences in correctness of the predicted IDs, higher value
  /// means higher confidence. Order matches the Ids.
  public var confidences: [Swift.Float] = []

  /// Initialize a new instance of `ClassificationPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClassificationPredictionResult().with { $0.ids = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ClassificationPredictionResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
