// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for CreateSearchConfig.
public struct CreateSearchConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this search configuration will be
  /// created. Format:
  /// `projects/{project_number}/locations/{location_id}/corpora/{corpus_id}`
  public var parent: Swift.String = Swift.String()

  /// Required. The search config to create.
  public var searchConfig: SearchConfig? = nil

  /// Required. ID to use for the new search config. Will become the final
  /// component of the SearchConfig's resource name. This value should be up to
  /// 63 characters, and valid characters are /[a-z][0-9]-_/. The first character
  /// must be a letter, the last could be a letter or a number.
  public var searchConfigId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateSearchConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSearchConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.CreateSearchConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
