// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Data schema indicates how the user specified annotation is interpreted in the
/// system.
public struct DataSchema: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Resource name of the data schema in the form of:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/dataSchemas/{data_schema}`
  /// where {data_schema} part should be the same as the `key` field below.
  public var name: Swift.String = Swift.String()

  /// Required. The key of this data schema. This key should be matching the key
  /// of user specified annotation and unique inside corpus. This value can be up
  /// to 63 characters, and valid characters are /[a-z][0-9]-/. The first
  /// character must be a letter, the last could be a letter or a number.
  public var key: Swift.String = Swift.String()

  /// The schema details mapping to the key.
  public var schemaDetails: DataSchemaDetails? = nil

  /// Initialize a new instance of `DataSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSchema().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.DataSchema"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
