// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleType

/// Definition of a single value with generic type.
public struct FacetValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `FacetValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FacetValue().with { $0.stringValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case stringValue = "stringValue"
    case integerValue = "integerValue"
    case datetimeValue = "datetimeValue"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try valueCheckAndSet(.stringValue(stringValue))
    }
    if let integerValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .integerValue) {
      try valueCheckAndSet(.integerValue(integerValue))
    }
    if let datetimeValue = try container.decodeIfPresent(
      GoogleType.DateTime?.self, forKey: .datetimeValue)
    {
      try valueCheckAndSet(.datetimeValue(datetimeValue))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.value {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .integerValue(let value):
        try container.encode(value, forKey: .integerValue)
      case .datetimeValue(let value):
        try container.encode(value, forKey: .datetimeValue)
      }
    }
  }

  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// String type value.
    case stringValue(Swift.String)
    /// Integer type value.
    case integerValue(Swift.Int64)
    /// Datetime type value.
    indirect case datetimeValue(GoogleType.DateTime?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.FacetValue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
