// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Prediction output format for Image Object Detection.
public struct ImageObjectDetectionPredictionResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource IDs of the AnnotationSpecs that had been identified, ordered
  /// by the confidence score descendingly. It is the id segment instead of full
  /// resource name.
  public var ids: [Swift.Int64] = []

  /// The display names of the AnnotationSpecs that had been identified, order
  /// matches the IDs.
  public var displayNames: [Swift.String] = []

  /// The Model's confidences in correctness of the predicted IDs, higher value
  /// means higher confidence. Order matches the Ids.
  public var confidences: [Swift.Float] = []

  /// Bounding boxes, i.e. the rectangles over the image, that pinpoint
  /// the found AnnotationSpecs. Given in order that matches the IDs. Each
  /// bounding box is an array of 4 numbers `xMin`, `xMax`, `yMin`, and
  /// `yMax`, which represent the extremal coordinates of the box. They are
  /// relative to the image size, and the point 0,0 is in the top left
  /// of the image.
  public var bboxes: [GoogleCloudWkt.ListValue] = []

  /// Initialize a new instance of `ImageObjectDetectionPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageObjectDetectionPredictionResult().with { $0.ids = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ImageObjectDetectionPredictionResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
