// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An IndexedAsset is an asset that the index is built upon.
public struct IndexedAsset: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The index that this indexed asset belongs to.
  /// Format:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/indexes/{index}`
  public var index: Swift.String = Swift.String()

  /// Required. The resource name of the asset.
  /// Format:
  /// `projects/{project_number}/locations/{location_id}/corpora/{corpus_id}/assets/{asset_id}`
  public var asset: Swift.String = Swift.String()

  /// Output only. The create timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The update timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `IndexedAsset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IndexedAsset().with { $0.index = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.IndexedAsset"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
