// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for IngestAsset API.
public struct IngestAssetRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  public var streamingRequest: OneOf_StreamingRequest? = nil

  /// Initialize a new instance of `IngestAssetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IngestAssetRequest().with { $0.config = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case config = "config"
    case timeIndexedData = "timeIndexedData"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var streamingRequest: OneOf_StreamingRequest? = nil
    let streamingRequestCheckAndSet = {
      if streamingRequest != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'streamingRequest'"))
      }
      streamingRequest = $0
    }
    if let config = try container.decodeIfPresent(IngestAssetRequest.Config?.self, forKey: .config)
    {
      try streamingRequestCheckAndSet(.config(config))
    }
    if let timeIndexedData = try container.decodeIfPresent(
      IngestAssetRequest.TimeIndexedData?.self, forKey: .timeIndexedData)
    {
      try streamingRequestCheckAndSet(.timeIndexedData(timeIndexedData))
    }
    self.streamingRequest = streamingRequest
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.streamingRequest {
      switch choice {
      case .config(let value):
        try container.encode(value, forKey: .config)
      case .timeIndexedData(let value):
        try container.encode(value, forKey: .timeIndexedData)
      }
    }
  }

  /// Configuration for the data.
  public struct Config: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the asset that the ingested data belongs
    /// to.
    public var asset: Swift.String = Swift.String()

    public var dataType: OneOf_DataType? = nil

    /// Initialize a new instance of `Config`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Config().with { $0.videoType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case videoType = "videoType"
      case asset = "asset"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.asset = try container.decode(Swift.String.self, forKey: .asset)

      var dataType: OneOf_DataType? = nil
      let dataTypeCheckAndSet = {
        if dataType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'dataType'"))
        }
        dataType = $0
      }
      if let videoType = try container.decodeIfPresent(
        IngestAssetRequest.Config.VideoType?.self, forKey: .videoType)
      {
        try dataTypeCheckAndSet(.videoType(videoType))
      }
      self.dataType = dataType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.asset, forKey: .asset)

      if let choice = self.dataType {
        switch choice {
        case .videoType(let value):
          try container.encode(value, forKey: .videoType)
        }
      }
    }

    /// Type information for video data.
    public struct VideoType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Container format of the video data.
      public var containerFormat: IngestAssetRequest.Config.VideoType.ContainerFormat =
        IngestAssetRequest.Config.VideoType.ContainerFormat()

      /// Initialize a new instance of `VideoType`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = VideoType().with { $0.containerFormat = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Container format of the video.
      public enum ContainerFormat: Codable, Equatable, Sendable {
        /// The default type, not supposed to be used.
        case unspecified
        /// Mp4 container format.
        case mp4
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .mp4: return 1
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "CONTAINER_FORMAT_UNSPECIFIED"
          case .mp4: return "CONTAINER_FORMAT_MP4"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContainerFormat/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "CONTAINER_FORMAT_UNSPECIFIED": self = .unspecified
          case "CONTAINER_FORMAT_MP4": self = .mp4
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContainerFormat/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .mp4
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .mp4: return try container.encode(1)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.visionai.v1.IngestAssetRequest.Config.VideoType"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_DataType: Codable, Equatable, Sendable {
      /// Type information for video data.
      indirect case videoType(IngestAssetRequest.Config.VideoType?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.IngestAssetRequest.Config"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Contains the data and the corresponding time range this data is for.
  public struct TimeIndexedData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Data to be ingested.
    public var data: Foundation.Data = Foundation.Data()

    /// Time range of the data.
    public var temporalPartition: Partition.TemporalPartition? = nil

    /// Initialize a new instance of `TimeIndexedData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeIndexedData().with { $0.data = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.IngestAssetRequest.TimeIndexedData"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_StreamingRequest: Codable, Equatable, Sendable {
    /// Provides information for the data and the asset resource name that the
    /// data belongs to. The first `IngestAssetRequest` message must only contain
    /// a `Config` message.
    indirect case config(IngestAssetRequest.Config?)
    /// Data to be ingested.
    indirect case timeIndexedData(IngestAssetRequest.TimeIndexedData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.IngestAssetRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
