// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for GetAnnotation API.
public struct ListAnnotationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The parent, which owns this collection of annotations.
  /// Format:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/assets/{asset}`
  public var parent: Swift.String = Swift.String()

  /// The maximum number of annotations to return. The service may return fewer
  /// than this value. If unspecified, at most 50 annotations will be returned.
  /// The maximum value is 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ListAnnotations` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ListAnnotations` must
  /// match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// The filter applied to the returned list.
  /// We only support filtering for the following fields:
  /// For corpus of STREAM_VIDEO type:
  /// `partition.temporal_partition.start_time`,
  /// `partition.temporal_partition.end_time`, and `key`.
  /// For corpus of VIDEO_ON_DEMAND type,
  /// `partition.relative_temporal_partition.start_offset`,
  /// `partition.relative_temporal_partition.end_offset`, and `key`.
  /// For corpus of IMAGE type, only `key` is supported.
  /// Timestamps are specified in the RFC-3339 format, and only one restriction
  /// may be applied per field, joined by conjunctions.
  /// Format:
  /// "partition.temporal_partition.start_time > "2012-04-21T11:30:00-04:00" AND
  /// partition.temporal_partition.end_time < "2012-04-22T11:30:00-04:00" AND
  /// key = "example_key""
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAnnotationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAnnotationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ListAnnotationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
