// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class LiveVideoAnalyticsRetry: LiveVideoAnalyticsStub {
    let inner: any LiveVideoAnalyticsStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any LiveVideoAnalyticsStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listPublicOperators(
      request: ListPublicOperatorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListPublicOperatorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPublicOperatorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListPublicOperatorsResponse
          in
          return try await self.inner.listPublicOperators(request: r, options: o)
        })
    }

    public func resolveOperatorInfo(
      request: ResolveOperatorInfoRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ResolveOperatorInfoResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResolveOperatorInfoRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ResolveOperatorInfoResponse
          in
          return try await self.inner.resolveOperatorInfo(request: r, options: o)
        })
    }

    public func listOperators(
      request: ListOperatorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListOperatorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOperatorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListOperatorsResponse
          in
          return try await self.inner.listOperators(request: r, options: o)
        })
    }

    public func getOperator(
      request: GetOperatorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Operator {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOperatorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Operator
          in
          return try await self.inner.getOperator(request: r, options: o)
        })
    }

    public func createOperator(
      request: CreateOperatorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateOperatorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createOperator(request: r, options: o)
        })
    }

    public func updateOperator(
      request: UpdateOperatorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateOperatorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateOperator(request: r, options: o)
        })
    }

    public func deleteOperator(
      request: DeleteOperatorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteOperatorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteOperator(request: r, options: o)
        })
    }

    public func listAnalyses(
      request: ListAnalysesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListAnalysesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAnalysesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListAnalysesResponse
          in
          return try await self.inner.listAnalyses(request: r, options: o)
        })
    }

    public func getAnalysis(
      request: GetAnalysisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Analysis {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAnalysisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Analysis
          in
          return try await self.inner.getAnalysis(request: r, options: o)
        })
    }

    public func createAnalysis(
      request: CreateAnalysisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAnalysisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAnalysis(request: r, options: o)
        })
    }

    public func updateAnalysis(
      request: UpdateAnalysisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAnalysisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAnalysis(request: r, options: o)
        })
    }

    public func deleteAnalysis(
      request: DeleteAnalysisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAnalysisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAnalysis(request: r, options: o)
        })
    }

    public func listProcesses(
      request: ListProcessesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListProcessesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListProcessesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.ListProcessesResponse
          in
          return try await self.inner.listProcesses(request: r, options: o)
        })
    }

    public func getProcess(
      request: GetProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Process {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudVideoAIV1.Process
          in
          return try await self.inner.getProcess(request: r, options: o)
        })
    }

    public func createProcess(
      request: CreateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createProcess(request: r, options: o)
        })
    }

    public func updateProcess(
      request: UpdateProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateProcess(request: r, options: o)
        })
    }

    public func deleteProcess(
      request: DeleteProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteProcess(request: r, options: o)
        })
    }

    public func batchRunProcess(
      request: BatchRunProcessRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchRunProcessRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchRunProcess(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
