// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// All the supported model types in Vision AI App Platform.
public enum ModelType: Codable, Equatable, Sendable {
  /// Processor Type UNSPECIFIED.
  case unspecified
  /// Model Type Image Classification.
  case imageClassification
  /// Model Type Object Detection.
  case objectDetection
  /// Model Type Video Classification.
  case videoClassification
  /// Model Type Object Tracking.
  case videoObjectTracking
  /// Model Type Action Recognition.
  case videoActionRecognition
  /// Model Type Occupancy Counting.
  case occupancyCounting
  /// Model Type Person Blur.
  case personBlur
  /// Model Type Vertex Custom.
  case vertexCustom
  /// Model Type Product Recognizer.
  case productRecognizer
  /// Model Type Tag Recognizer.
  case tagRecognizer
  /// Model Type SynthID.
  case synthId
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .imageClassification: return 1
    case .objectDetection: return 2
    case .videoClassification: return 3
    case .videoObjectTracking: return 4
    case .videoActionRecognition: return 5
    case .occupancyCounting: return 6
    case .personBlur: return 7
    case .vertexCustom: return 8
    case .productRecognizer: return 9
    case .tagRecognizer: return 10
    case .synthId: return 15
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
    case .imageClassification: return "IMAGE_CLASSIFICATION"
    case .objectDetection: return "OBJECT_DETECTION"
    case .videoClassification: return "VIDEO_CLASSIFICATION"
    case .videoObjectTracking: return "VIDEO_OBJECT_TRACKING"
    case .videoActionRecognition: return "VIDEO_ACTION_RECOGNITION"
    case .occupancyCounting: return "OCCUPANCY_COUNTING"
    case .personBlur: return "PERSON_BLUR"
    case .vertexCustom: return "VERTEX_CUSTOM"
    case .productRecognizer: return "PRODUCT_RECOGNIZER"
    case .tagRecognizer: return "TAG_RECOGNIZER"
    case .synthId: return "SYNTH_ID"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
    case "IMAGE_CLASSIFICATION": self = .imageClassification
    case "OBJECT_DETECTION": self = .objectDetection
    case "VIDEO_CLASSIFICATION": self = .videoClassification
    case "VIDEO_OBJECT_TRACKING": self = .videoObjectTracking
    case "VIDEO_ACTION_RECOGNITION": self = .videoActionRecognition
    case "OCCUPANCY_COUNTING": self = .occupancyCounting
    case "PERSON_BLUR": self = .personBlur
    case "VERTEX_CUSTOM": self = .vertexCustom
    case "PRODUCT_RECOGNIZER": self = .productRecognizer
    case "TAG_RECOGNIZER": self = .tagRecognizer
    case "SYNTH_ID": self = .synthId
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .imageClassification
    case 2: self = .objectDetection
    case 3: self = .videoClassification
    case 4: self = .videoObjectTracking
    case 5: self = .videoActionRecognition
    case 6: self = .occupancyCounting
    case 7: self = .personBlur
    case 8: self = .vertexCustom
    case 9: self = .productRecognizer
    case 10: self = .tagRecognizer
    case 15: self = .synthId
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .imageClassification: return try container.encode(1)
    case .objectDetection: return try container.encode(2)
    case .videoClassification: return try container.encode(3)
    case .videoObjectTracking: return try container.encode(4)
    case .videoActionRecognition: return try container.encode(5)
    case .occupancyCounting: return try container.encode(6)
    case .personBlur: return try container.encode(7)
    case .vertexCustom: return try container.encode(8)
    case .productRecognizer: return try container.encode(9)
    case .tagRecognizer: return try container.encode(10)
    case .synthId: return try container.encode(15)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
