// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines the interface of an Operator.
///
/// Arguments to an operator are input/output streams that are getting
/// processesed/returned while attributes are fixed configuration parameters.
public struct OperatorDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of this operator.
  ///
  /// Tentatively [A-Z][a-zA-Z0-9]*, e.g., BboxCounter, PetDetector,
  /// PetDetector1.
  public var `operator`: Swift.String = Swift.String()

  /// Declares input arguments.
  public var inputArgs: [OperatorDefinition.ArgumentDefinition] = []

  /// Declares output arguments.
  public var outputArgs: [OperatorDefinition.ArgumentDefinition] = []

  /// Declares the attributes.
  public var attributes: [OperatorDefinition.AttributeDefinition] = []

  /// The resources for running the operator.
  public var resources: ResourceSpecification? = nil

  /// Short description of the operator.
  public var shortDescription: Swift.String = Swift.String()

  /// Full description of the operator.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `OperatorDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperatorDefinition().with { $0.`operator` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `operator` = "operator"
    case inputArgs = "inputArgs"
    case outputArgs = "outputArgs"
    case attributes = "attributes"
    case resources = "resources"
    case shortDescription = "shortDescription"
    case description = "description"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`operator` = try container.decode(Swift.String.self, forKey: .`operator`)
    self.inputArgs = try container.decode(
      [OperatorDefinition.ArgumentDefinition].self, forKey: .inputArgs)
    self.outputArgs = try container.decode(
      [OperatorDefinition.ArgumentDefinition].self, forKey: .outputArgs)
    self.attributes = try container.decode(
      [OperatorDefinition.AttributeDefinition].self, forKey: .attributes)
    self.resources = try container.decodeIfPresent(ResourceSpecification.self, forKey: .resources)
    self.shortDescription = try container.decode(Swift.String.self, forKey: .shortDescription)
    self.description = try container.decode(Swift.String.self, forKey: .description)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`operator`, forKey: .`operator`)
    try container.encode(self.inputArgs, forKey: .inputArgs)
    try container.encode(self.outputArgs, forKey: .outputArgs)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.resources, forKey: .resources)
    try container.encode(self.shortDescription, forKey: .shortDescription)
    try container.encode(self.description, forKey: .description)
  }

  /// Defines an argument to an operator.
  ///
  /// Used for both inputs and outputs.
  public struct ArgumentDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the argument.
    ///
    /// Tentatively [a-z]([_a-z0-9]*[a-z0-9])?, e.g., video, audio,
    /// high_fps_frame.
    public var argument: Swift.String = Swift.String()

    /// The data type of the argument.
    ///
    /// This should match the textual representation of a stream/Packet type.
    public var type: Swift.String = Swift.String()

    /// Initialize a new instance of `ArgumentDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ArgumentDefinition().with { $0.argument = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.OperatorDefinition.ArgumentDefinition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines an attribute of an operator.
  public struct AttributeDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the attribute.
    ///
    /// Tentatively [a-z]([_a-z0-9]*[a-z0-9])?, e.g., max_frames_per_video,
    /// resize_height.
    public var attribute: Swift.String = Swift.String()

    /// The type of this attribute.
    ///
    /// See attribute_value.proto for possibilities.
    public var type: Swift.String = Swift.String()

    /// The default value for the attribute.
    public var defaultValue: AttributeValue? = nil

    /// Initialize a new instance of `AttributeDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AttributeDefinition().with { $0.attribute = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.OperatorDefinition.AttributeDefinition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.OperatorDefinition"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
