// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The message that represents the data type of a packet.
public struct PacketType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type class of the packet. Its possible values are:
  /// "gst", "protobuf", and "string".
  public var typeClass: Swift.String = Swift.String()

  /// The type descriptor.
  public var typeDescriptor: PacketType.TypeDescriptor? = nil

  /// Initialize a new instance of `PacketType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PacketType().with { $0.typeClass = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The message that fully specifies the type of the packet.
  public struct TypeDescriptor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The type of the packet. Its possible values is codec dependent.
    ///
    /// The fully qualified type name is always the concatenation of the
    /// value in `type_class` together with the value in `type`, separated by a
    /// '/'.
    ///
    /// Note that specific codecs can define their own type hierarchy, and so the
    /// type string here can in fact be separated by multiple '/'s of its own.
    ///
    /// Please see the open source SDK for specific codec documentation.
    public var type: Swift.String = Swift.String()

    /// Detailed information about the type.
    ///
    /// It is non-empty only for specific type class codecs. Needed only when the
    /// type string alone is not enough to disambiguate the specific type.
    public var typeDetails: OneOf_TypeDetails? = nil

    /// Initialize a new instance of `TypeDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TypeDescriptor().with { $0.gstreamerBufferDescriptor = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case gstreamerBufferDescriptor = "gstreamerBufferDescriptor"
      case rawImageDescriptor = "rawImageDescriptor"
      case type = "type"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.type = try container.decode(Swift.String.self, forKey: .type)

      var typeDetails: OneOf_TypeDetails? = nil
      let typeDetailsCheckAndSet = {
        if typeDetails != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'typeDetails'"))
        }
        typeDetails = $0
      }
      if let gstreamerBufferDescriptor = try container.decodeIfPresent(
        GstreamerBufferDescriptor?.self, forKey: .gstreamerBufferDescriptor)
      {
        try typeDetailsCheckAndSet(.gstreamerBufferDescriptor(gstreamerBufferDescriptor))
      }
      if let rawImageDescriptor = try container.decodeIfPresent(
        RawImageDescriptor?.self, forKey: .rawImageDescriptor)
      {
        try typeDetailsCheckAndSet(.rawImageDescriptor(rawImageDescriptor))
      }
      self.typeDetails = typeDetails
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)

      if let choice = self.typeDetails {
        switch choice {
        case .gstreamerBufferDescriptor(let value):
          try container.encode(value, forKey: .gstreamerBufferDescriptor)
        case .rawImageDescriptor(let value):
          try container.encode(value, forKey: .rawImageDescriptor)
        }
      }
    }

    /// Detailed information about the type.
    ///
    /// It is non-empty only for specific type class codecs. Needed only when the
    /// type string alone is not enough to disambiguate the specific type.
    public enum OneOf_TypeDetails: Codable, Equatable, Sendable {
      /// GstreamerBufferDescriptor is the descriptor for gstreamer buffer type.
      indirect case gstreamerBufferDescriptor(GstreamerBufferDescriptor?)
      /// RawImageDescriptor is the descriptor for the raw image type.
      indirect case rawImageDescriptor(RawImageDescriptor?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.PacketType.TypeDescriptor"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.PacketType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
