// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The message that represents packet header.
public struct PacketHeader: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Input only. The capture time of the packet.
  public var captureTime: GoogleCloudWkt.Timestamp? = nil

  /// Input only. Immutable. The type of the payload.
  public var type: PacketType? = nil

  /// Input only. This field is for users to attach user managed metadata.
  public var metadata: GoogleCloudWkt.Struct? = nil

  /// Output only. Metadata that the server appends to each packet before sending
  /// it to receivers. You don't need to set a value for this field when sending
  /// packets.
  public var serverMetadata: ServerMetadata? = nil

  /// Input only. Immutable. Metadata that the server needs to know where to
  /// write the packets to. It's only required for the first packet.
  public var seriesMetadata: SeriesMetadata? = nil

  /// Immutable. Packet flag set. SDK will set the flag automatically.
  public var flags: Swift.Int32 = Swift.Int32()

  /// Immutable. Header string for tracing across services. It should be set when
  /// the packet is first arrived in the stream server.
  ///
  /// The input format is a lowercase hex string:
  ///   - version_id: 1 byte, currently must be zero - hex encoded (2 characters)
  ///   - trace_id: 16 bytes (opaque blob) - hex encoded (32 characters)
  ///   - span_id: 8 bytes (opaque blob) - hex encoded (16 characters)
  ///   - trace_options: 1 byte (LSB means tracing enabled) - hex encoded (2
  ///   characters)
  /// Example: "00-404142434445464748494a4b4c4d4e4f-6162636465666768-01"
  ///           v  trace_id                         span_id          options
  public var traceContext: Swift.String = Swift.String()

  /// Initialize a new instance of `PacketHeader`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PacketHeader().with { $0.captureTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.PacketHeader"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
