// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Partition to specify the partition in time and space for sub-asset level
/// annotation.
public struct Partition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Partition of asset in time.
  public var temporalPartition: Partition.TemporalPartition? = nil

  /// Partition of asset in space.
  public var spatialPartition: Partition.SpatialPartition? = nil

  /// Partition of asset in time.
  public var relativeTemporalPartition: Partition.RelativeTemporalPartition? = nil

  /// Initialize a new instance of `Partition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Partition().with { $0.temporalPartition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Partition of asset in UTC Epoch time. Supported by STREAM_VIDEO corpus
  /// type.
  public struct TemporalPartition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Start time of the partition.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// End time of the partition.
    public var endTime: GoogleCloudWkt.Timestamp? = nil

    /// Initialize a new instance of `TemporalPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TemporalPartition().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.TemporalPartition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Partition of asset in space.
  public struct SpatialPartition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The minimum x coordinate value.
    public var xMin: Swift.Int64? = nil

    /// The minimum y coordinate value.
    public var yMin: Swift.Int64? = nil

    /// The maximum x coordinate value.
    public var xMax: Swift.Int64? = nil

    /// The maximum y coordinate value.
    public var yMax: Swift.Int64? = nil

    /// Initialize a new instance of `SpatialPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SpatialPartition().with { $0.xMin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.SpatialPartition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Partition of asset in relative time. Supported by VIDEO_ON_DEMAND corpus
  /// type.
  public struct RelativeTemporalPartition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Start time offset of the partition.
    public var startOffset: GoogleCloudWkt.Duration? = nil

    /// End time offset of the partition.
    public var endOffset: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `RelativeTemporalPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RelativeTemporalPartition().with { $0.startOffset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.RelativeTemporalPartition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Partition"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
