// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Output format for Personal Protective Equipment Detection Operator.
public struct PersonalProtectiveEquipmentDetectionOutput: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Current timestamp.
  public var currentTime: GoogleCloudWKT.Timestamp? = nil

  /// A list of DetectedPersons.
  public var detectedPersons: [PersonalProtectiveEquipmentDetectionOutput.DetectedPerson] = []

  /// Initialize a new instance of `PersonalProtectiveEquipmentDetectionOutput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PersonalProtectiveEquipmentDetectionOutput().with { $0.currentTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The entity info for annotations from person detection prediction result.
  public struct PersonEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Entity id.
    public var personEntityId: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `PersonEntity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PersonEntity().with { $0.personEntityId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PersonEntity"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The entity info for annotations from PPE detection prediction result.
  public struct PPEEntity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Label id.
    public var ppeLabelId: Swift.Int64 = Swift.Int64()

    /// Human readable string of the label (Examples: helmet, glove, mask).
    public var ppeLabelString: Swift.String = Swift.String()

    /// Human readable string of the super category label (Examples: head_cover,
    /// hands_cover, face_cover).
    public var ppeSupercategoryLabelString: Swift.String = Swift.String()

    /// Entity id.
    public var ppeEntityId: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `PPEEntity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PPEEntity().with { $0.ppeLabelId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PPEEntity"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Bounding Box in the normalized coordinates.
  public struct NormalizedBoundingBox: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Min in x coordinate.
    public var xmin: Swift.Float = Swift.Float()

    /// Min in y coordinate.
    public var ymin: Swift.Float = Swift.Float()

    /// Width of the bounding box.
    public var width: Swift.Float = Swift.Float()

    /// Height of the bounding box.
    public var height: Swift.Float = Swift.Float()

    /// Initialize a new instance of `NormalizedBoundingBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NormalizedBoundingBox().with { $0.xmin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// PersonIdentified box contains the location and the entity info of the
  /// person.
  public struct PersonIdentifiedBox: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// An unique id for this box.
    public var boxId: Swift.Int64 = Swift.Int64()

    /// Bounding Box in the normalized coordinates.
    public var normalizedBoundingBox:
      PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox? = nil

    /// Confidence score associated with this box.
    public var confidenceScore: Swift.Float = Swift.Float()

    /// Person entity info.
    public var personEntity: PersonalProtectiveEquipmentDetectionOutput.PersonEntity? = nil

    /// Initialize a new instance of `PersonIdentifiedBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PersonIdentifiedBox().with { $0.boxId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PersonIdentifiedBox"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// PPEIdentified box contains the location and the entity info of the PPE.
  public struct PPEIdentifiedBox: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// An unique id for this box.
    public var boxId: Swift.Int64 = Swift.Int64()

    /// Bounding Box in the normalized coordinates.
    public var normalizedBoundingBox:
      PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox? = nil

    /// Confidence score associated with this box.
    public var confidenceScore: Swift.Float = Swift.Float()

    /// PPE entity info.
    public var ppeEntity: PersonalProtectiveEquipmentDetectionOutput.PPEEntity? = nil

    /// Initialize a new instance of `PPEIdentifiedBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PPEIdentifiedBox().with { $0.boxId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PPEIdentifiedBox"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Detected Person contains the detected person and their associated
  /// ppes and their protecting information.
  public struct DetectedPerson: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The id of detected person.
    public var personId: Swift.Int64 = Swift.Int64()

    /// The info of detected person identified box.
    public var detectedPersonIdentifiedBox:
      PersonalProtectiveEquipmentDetectionOutput.PersonIdentifiedBox? = nil

    /// The info of detected person associated ppe identified boxes.
    public var detectedPpeIdentifiedBoxes:
      [PersonalProtectiveEquipmentDetectionOutput.PPEIdentifiedBox] = []

    /// Coverage score for each body part.
    /// Coverage score for face.
    public var faceCoverageScore: Swift.Float? = nil

    /// Coverage score for eyes.
    public var eyesCoverageScore: Swift.Float? = nil

    /// Coverage score for head.
    public var headCoverageScore: Swift.Float? = nil

    /// Coverage score for hands.
    public var handsCoverageScore: Swift.Float? = nil

    /// Coverage score for body.
    public var bodyCoverageScore: Swift.Float? = nil

    /// Coverage score for feet.
    public var feetCoverageScore: Swift.Float? = nil

    /// Initialize a new instance of `DetectedPerson`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedPerson().with { $0.personId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.DetectedPerson"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
