// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Next ID: 35
public struct ProcessorConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Experimental configurations. Structured object containing not-yet-stable
  /// processor parameters.
  public var experimentalConfig: GoogleCloudWKT.Struct? = nil

  public var processorConfig: OneOf_ProcessorConfig? = nil

  /// Initialize a new instance of `ProcessorConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessorConfig().with { $0.videoStreamInputConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case videoStreamInputConfig = "videoStreamInputConfig"
    case aiEnabledDevicesInputConfig = "aiEnabledDevicesInputConfig"
    case mediaWarehouseConfig = "mediaWarehouseConfig"
    case personBlurConfig = "personBlurConfig"
    case occupancyCountConfig = "occupancyCountConfig"
    case personVehicleDetectionConfig = "personVehicleDetectionConfig"
    case vertexAutomlVisionConfig = "vertexAutomlVisionConfig"
    case vertexAutomlVideoConfig = "vertexAutomlVideoConfig"
    case vertexCustomConfig = "vertexCustomConfig"
    case generalObjectDetectionConfig = "generalObjectDetectionConfig"
    case bigQueryConfig = "bigQueryConfig"
    case gcsOutputConfig = "gcsOutputConfig"
    case productRecognizerConfig = "productRecognizerConfig"
    case personalProtectiveEquipmentDetectionConfig = "personalProtectiveEquipmentDetectionConfig"
    case tagRecognizerConfig = "tagRecognizerConfig"
    case universalInputConfig = "universalInputConfig"
    case experimentalConfig = "experimentalConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.experimentalConfig = try container.decodeIfPresent(
      GoogleCloudWKT.Struct.self, forKey: .experimentalConfig)

    var processorConfig: OneOf_ProcessorConfig? = nil
    let processorConfigCheckAndSet = {
      if processorConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'processorConfig'"))
      }
      processorConfig = $0
    }
    if let videoStreamInputConfig = try container.decodeIfPresent(
      VideoStreamInputConfig?.self, forKey: .videoStreamInputConfig)
    {
      try processorConfigCheckAndSet(.videoStreamInputConfig(videoStreamInputConfig))
    }
    if let aiEnabledDevicesInputConfig = try container.decodeIfPresent(
      AIEnabledDevicesInputConfig?.self, forKey: .aiEnabledDevicesInputConfig)
    {
      try processorConfigCheckAndSet(.aiEnabledDevicesInputConfig(aiEnabledDevicesInputConfig))
    }
    if let mediaWarehouseConfig = try container.decodeIfPresent(
      MediaWarehouseConfig?.self, forKey: .mediaWarehouseConfig)
    {
      try processorConfigCheckAndSet(.mediaWarehouseConfig(mediaWarehouseConfig))
    }
    if let personBlurConfig = try container.decodeIfPresent(
      PersonBlurConfig?.self, forKey: .personBlurConfig)
    {
      try processorConfigCheckAndSet(.personBlurConfig(personBlurConfig))
    }
    if let occupancyCountConfig = try container.decodeIfPresent(
      OccupancyCountConfig?.self, forKey: .occupancyCountConfig)
    {
      try processorConfigCheckAndSet(.occupancyCountConfig(occupancyCountConfig))
    }
    if let personVehicleDetectionConfig = try container.decodeIfPresent(
      PersonVehicleDetectionConfig?.self, forKey: .personVehicleDetectionConfig)
    {
      try processorConfigCheckAndSet(.personVehicleDetectionConfig(personVehicleDetectionConfig))
    }
    if let vertexAutomlVisionConfig = try container.decodeIfPresent(
      VertexAutoMLVisionConfig?.self, forKey: .vertexAutomlVisionConfig)
    {
      try processorConfigCheckAndSet(.vertexAutomlVisionConfig(vertexAutomlVisionConfig))
    }
    if let vertexAutomlVideoConfig = try container.decodeIfPresent(
      VertexAutoMLVideoConfig?.self, forKey: .vertexAutomlVideoConfig)
    {
      try processorConfigCheckAndSet(.vertexAutomlVideoConfig(vertexAutomlVideoConfig))
    }
    if let vertexCustomConfig = try container.decodeIfPresent(
      VertexCustomConfig?.self, forKey: .vertexCustomConfig)
    {
      try processorConfigCheckAndSet(.vertexCustomConfig(vertexCustomConfig))
    }
    if let generalObjectDetectionConfig = try container.decodeIfPresent(
      GeneralObjectDetectionConfig?.self, forKey: .generalObjectDetectionConfig)
    {
      try processorConfigCheckAndSet(.generalObjectDetectionConfig(generalObjectDetectionConfig))
    }
    if let bigQueryConfig = try container.decodeIfPresent(
      BigQueryConfig?.self, forKey: .bigQueryConfig)
    {
      try processorConfigCheckAndSet(.bigQueryConfig(bigQueryConfig))
    }
    if let gcsOutputConfig = try container.decodeIfPresent(
      GcsOutputConfig?.self, forKey: .gcsOutputConfig)
    {
      try processorConfigCheckAndSet(.gcsOutputConfig(gcsOutputConfig))
    }
    if let productRecognizerConfig = try container.decodeIfPresent(
      ProductRecognizerConfig?.self, forKey: .productRecognizerConfig)
    {
      try processorConfigCheckAndSet(.productRecognizerConfig(productRecognizerConfig))
    }
    if let personalProtectiveEquipmentDetectionConfig = try container.decodeIfPresent(
      PersonalProtectiveEquipmentDetectionConfig?.self,
      forKey: .personalProtectiveEquipmentDetectionConfig)
    {
      try processorConfigCheckAndSet(
        .personalProtectiveEquipmentDetectionConfig(personalProtectiveEquipmentDetectionConfig))
    }
    if let tagRecognizerConfig = try container.decodeIfPresent(
      TagRecognizerConfig?.self, forKey: .tagRecognizerConfig)
    {
      try processorConfigCheckAndSet(.tagRecognizerConfig(tagRecognizerConfig))
    }
    if let universalInputConfig = try container.decodeIfPresent(
      UniversalInputConfig?.self, forKey: .universalInputConfig)
    {
      try processorConfigCheckAndSet(.universalInputConfig(universalInputConfig))
    }
    self.processorConfig = processorConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.experimentalConfig, forKey: .experimentalConfig)

    if let choice = self.processorConfig {
      switch choice {
      case .videoStreamInputConfig(let value):
        try container.encode(value, forKey: .videoStreamInputConfig)
      case .aiEnabledDevicesInputConfig(let value):
        try container.encode(value, forKey: .aiEnabledDevicesInputConfig)
      case .mediaWarehouseConfig(let value):
        try container.encode(value, forKey: .mediaWarehouseConfig)
      case .personBlurConfig(let value):
        try container.encode(value, forKey: .personBlurConfig)
      case .occupancyCountConfig(let value):
        try container.encode(value, forKey: .occupancyCountConfig)
      case .personVehicleDetectionConfig(let value):
        try container.encode(value, forKey: .personVehicleDetectionConfig)
      case .vertexAutomlVisionConfig(let value):
        try container.encode(value, forKey: .vertexAutomlVisionConfig)
      case .vertexAutomlVideoConfig(let value):
        try container.encode(value, forKey: .vertexAutomlVideoConfig)
      case .vertexCustomConfig(let value):
        try container.encode(value, forKey: .vertexCustomConfig)
      case .generalObjectDetectionConfig(let value):
        try container.encode(value, forKey: .generalObjectDetectionConfig)
      case .bigQueryConfig(let value):
        try container.encode(value, forKey: .bigQueryConfig)
      case .gcsOutputConfig(let value):
        try container.encode(value, forKey: .gcsOutputConfig)
      case .productRecognizerConfig(let value):
        try container.encode(value, forKey: .productRecognizerConfig)
      case .personalProtectiveEquipmentDetectionConfig(let value):
        try container.encode(value, forKey: .personalProtectiveEquipmentDetectionConfig)
      case .tagRecognizerConfig(let value):
        try container.encode(value, forKey: .tagRecognizerConfig)
      case .universalInputConfig(let value):
        try container.encode(value, forKey: .universalInputConfig)
      }
    }
  }

  public enum OneOf_ProcessorConfig: Codable, Equatable, Sendable {
    /// Configs of stream input processor.
    indirect case videoStreamInputConfig(VideoStreamInputConfig?)
    /// Config of AI-enabled input devices.
    indirect case aiEnabledDevicesInputConfig(AIEnabledDevicesInputConfig?)
    /// Configs of media warehouse processor.
    indirect case mediaWarehouseConfig(MediaWarehouseConfig?)
    /// Configs of person blur processor.
    indirect case personBlurConfig(PersonBlurConfig?)
    /// Configs of occupancy count processor.
    indirect case occupancyCountConfig(OccupancyCountConfig?)
    /// Configs of Person Vehicle Detection processor.
    indirect case personVehicleDetectionConfig(PersonVehicleDetectionConfig?)
    /// Configs of Vertex AutoML vision processor.
    indirect case vertexAutomlVisionConfig(VertexAutoMLVisionConfig?)
    /// Configs of Vertex AutoML video processor.
    indirect case vertexAutomlVideoConfig(VertexAutoMLVideoConfig?)
    /// Configs of Vertex Custom processor.
    indirect case vertexCustomConfig(VertexCustomConfig?)
    /// Configs of General Object Detection processor.
    indirect case generalObjectDetectionConfig(GeneralObjectDetectionConfig?)
    /// Configs of BigQuery processor.
    indirect case bigQueryConfig(BigQueryConfig?)
    /// Configs of Cloud Storage output processor.
    indirect case gcsOutputConfig(GcsOutputConfig?)
    /// Runtime configs of Product Recognizer processor.
    indirect case productRecognizerConfig(ProductRecognizerConfig?)
    /// Configs of personal_protective_equipment_detection_config
    indirect case personalProtectiveEquipmentDetectionConfig(
      PersonalProtectiveEquipmentDetectionConfig?)
    /// Runtime configs of Tag Recognizer processor.
    indirect case tagRecognizerConfig(TagRecognizerConfig?)
    /// Runtime configs of UniversalInput processor.
    indirect case universalInputConfig(UniversalInputConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ProcessorConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
