// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message from ReceivePackets.
public struct ReceivePacketsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Possible response types.
  public var response: OneOf_Response? = nil

  /// Initialize a new instance of `ReceivePacketsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceivePacketsResponse().with { $0.packet = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case packet = "packet"
    case control = "control"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var response: OneOf_Response? = nil
    let responseCheckAndSet = {
      if response != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'response'"))
      }
      response = $0
    }
    if let packet = try container.decodeIfPresent(Packet?.self, forKey: .packet) {
      try responseCheckAndSet(.packet(packet))
    }
    if let control = try container.decodeIfPresent(
      ReceivePacketsControlResponse?.self, forKey: .control)
    {
      try responseCheckAndSet(.control(control))
    }
    self.response = response
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.response {
      switch choice {
      case .packet(let value):
        try container.encode(value, forKey: .packet)
      case .control(let value):
        try container.encode(value, forKey: .control)
      }
    }
  }

  /// Possible response types.
  public enum OneOf_Response: Codable, Equatable, Sendable {
    /// A genuine data payload originating from the sender.
    indirect case packet(Packet?)
    /// A control message from the server.
    indirect case control(ReceivePacketsControlResponse?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
