// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for ReceiveEvents.
public struct ReceiveEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var request: OneOf_Request? = nil

  /// Initialize a new instance of `ReceiveEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceiveEventsRequest().with { $0.setupRequest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case setupRequest = "setupRequest"
    case commitRequest = "commitRequest"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var request: OneOf_Request? = nil
    let requestCheckAndSet = {
      if request != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'request'"))
      }
      request = $0
    }
    if let setupRequest = try container.decodeIfPresent(
      ReceiveEventsRequest.SetupRequest?.self, forKey: .setupRequest)
    {
      try requestCheckAndSet(.setupRequest(setupRequest))
    }
    if let commitRequest = try container.decodeIfPresent(
      CommitRequest?.self, forKey: .commitRequest)
    {
      try requestCheckAndSet(.commitRequest(commitRequest))
    }
    self.request = request
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.request {
      switch choice {
      case .setupRequest(let value):
        try container.encode(value, forKey: .setupRequest)
      case .commitRequest(let value):
        try container.encode(value, forKey: .commitRequest)
      }
    }
  }

  /// SetupRequest is the first message sent to the service to setup the RPC
  /// connection.
  public struct SetupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The cluster name.
    public var cluster: Swift.String = Swift.String()

    /// The stream name. The service will return the events for the given stream.
    public var stream: Swift.String = Swift.String()

    /// A name for the receiver to self-identify.
    ///
    /// This is used to keep track of a receiver's read progress.
    public var receiver: Swift.String = Swift.String()

    /// Controller mode configuration for receiving events from the server.
    public var controlledMode: ControlledMode? = nil

    /// The maximum duration of server silence before the client determines the
    /// server unreachable.
    ///
    /// The client must either receive an `Event` update or a heart beat message
    /// before this duration expires; otherwise, the client will automatically
    /// cancel the current connection and retry.
    public var heartbeatInterval: GoogleCloudWkt.Duration? = nil

    /// The grace period after which a `writes_done_request` is issued, that a
    /// `WritesDone` is expected from the client.
    ///
    /// The server is free to cancel the RPC should this expire.
    ///
    /// A system default will be chosen if unset.
    public var writesDoneGracePeriod: GoogleCloudWkt.Duration? = nil

    /// Initialize a new instance of `SetupRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SetupRequest().with { $0.cluster = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsRequest.SetupRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_Request: Codable, Equatable, Sendable {
    /// The setup request to setup the RPC connection.
    indirect case setupRequest(ReceiveEventsRequest.SetupRequest?)
    /// This request checkpoints the consumer's read progress.
    indirect case commitRequest(CommitRequest?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
