// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for the ReceiveEvents.
public struct ReceiveEventsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Possible response types.
  public var response: OneOf_Response? = nil

  /// Initialize a new instance of `ReceiveEventsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceiveEventsResponse().with { $0.eventUpdate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case eventUpdate = "eventUpdate"
    case control = "control"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var response: OneOf_Response? = nil
    let responseCheckAndSet = {
      if response != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'response'"))
      }
      response = $0
    }
    if let eventUpdate = try container.decodeIfPresent(EventUpdate?.self, forKey: .eventUpdate) {
      try responseCheckAndSet(.eventUpdate(eventUpdate))
    }
    if let control = try container.decodeIfPresent(
      ReceiveEventsControlResponse?.self, forKey: .control)
    {
      try responseCheckAndSet(.control(control))
    }
    self.response = response
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.response {
      switch choice {
      case .eventUpdate(let value):
        try container.encode(value, forKey: .eventUpdate)
      case .control(let value):
        try container.encode(value, forKey: .control)
      }
    }
  }

  /// Possible response types.
  public enum OneOf_Response: Codable, Equatable, Sendable {
    /// The event update message.
    indirect case eventUpdate(EventUpdate?)
    /// A control message from the server.
    indirect case control(ReceiveEventsControlResponse?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
