// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for receiving packets.
public struct ReceivePacketsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Possible request types from the client.
  public var request: OneOf_Request? = nil

  /// Initialize a new instance of `ReceivePacketsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceivePacketsRequest().with { $0.setupRequest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case setupRequest = "setupRequest"
    case commitRequest = "commitRequest"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var request: OneOf_Request? = nil
    let requestCheckAndSet = {
      if request != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'request'"))
      }
      request = $0
    }
    if let setupRequest = try container.decodeIfPresent(
      ReceivePacketsRequest.SetupRequest?.self, forKey: .setupRequest)
    {
      try requestCheckAndSet(.setupRequest(setupRequest))
    }
    if let commitRequest = try container.decodeIfPresent(
      CommitRequest?.self, forKey: .commitRequest)
    {
      try requestCheckAndSet(.commitRequest(commitRequest))
    }
    self.request = request
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.request {
      switch choice {
      case .setupRequest(let value):
        try container.encode(value, forKey: .setupRequest)
      case .commitRequest(let value):
        try container.encode(value, forKey: .commitRequest)
      }
    }
  }

  /// The message specifying the initial settings for the ReceivePackets session.
  public struct SetupRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The configurations that specify where packets are retrieved.
    public var metadata: RequestMetadata? = nil

    /// A name for the receiver to self-identify.
    ///
    /// This is used to keep track of a receiver's read progress.
    public var receiver: Swift.String = Swift.String()

    /// The maximum duration of server silence before the client determines the
    /// server unreachable.
    ///
    /// The client must either receive a `Packet` or a heart beat message before
    /// this duration expires; otherwise, the client will automatically cancel
    /// the current connection and retry.
    public var heartbeatInterval: GoogleCloudWKT.Duration? = nil

    /// The grace period after which a `writes_done_request` is issued, that a
    /// `WritesDone` is expected from the client.
    ///
    /// The server is free to cancel the RPC should this expire.
    ///
    /// A system default will be chosen if unset.
    public var writesDoneGracePeriod: GoogleCloudWKT.Duration? = nil

    /// The mode in which the consumer reads messages.
    public var consumerMode: OneOf_ConsumerMode? = nil

    /// Initialize a new instance of `SetupRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SetupRequest().with { $0.eagerReceiveMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case eagerReceiveMode = "eagerReceiveMode"
      case controlledReceiveMode = "controlledReceiveMode"
      case metadata = "metadata"
      case receiver = "receiver"
      case heartbeatInterval = "heartbeatInterval"
      case writesDoneGracePeriod = "writesDoneGracePeriod"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.metadata = try container.decodeIfPresent(RequestMetadata.self, forKey: .metadata)
      self.receiver = try container.decode(Swift.String.self, forKey: .receiver)
      self.heartbeatInterval = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .heartbeatInterval)
      self.writesDoneGracePeriod = try container.decodeIfPresent(
        GoogleCloudWKT.Duration.self, forKey: .writesDoneGracePeriod)

      var consumerMode: OneOf_ConsumerMode? = nil
      let consumerModeCheckAndSet = {
        if consumerMode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'consumerMode'"))
        }
        consumerMode = $0
      }
      if let eagerReceiveMode = try container.decodeIfPresent(
        EagerMode?.self, forKey: .eagerReceiveMode)
      {
        try consumerModeCheckAndSet(.eagerReceiveMode(eagerReceiveMode))
      }
      if let controlledReceiveMode = try container.decodeIfPresent(
        ControlledMode?.self, forKey: .controlledReceiveMode)
      {
        try consumerModeCheckAndSet(.controlledReceiveMode(controlledReceiveMode))
      }
      self.consumerMode = consumerMode
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.metadata, forKey: .metadata)
      try container.encode(self.receiver, forKey: .receiver)
      try container.encode(self.heartbeatInterval, forKey: .heartbeatInterval)
      try container.encode(self.writesDoneGracePeriod, forKey: .writesDoneGracePeriod)

      if let choice = self.consumerMode {
        switch choice {
        case .eagerReceiveMode(let value):
          try container.encode(value, forKey: .eagerReceiveMode)
        case .controlledReceiveMode(let value):
          try container.encode(value, forKey: .controlledReceiveMode)
        }
      }
    }

    /// The mode in which the consumer reads messages.
    public enum OneOf_ConsumerMode: Codable, Equatable, Sendable {
      /// Options for configuring eager mode.
      indirect case eagerReceiveMode(EagerMode?)
      /// Options for configuring controlled mode.
      indirect case controlledReceiveMode(ControlledMode?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest.SetupRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible request types from the client.
  public enum OneOf_Request: Codable, Equatable, Sendable {
    /// The request to setup the initial state of session.
    ///
    /// The client must send and only send this as the first message.
    indirect case setupRequest(ReceivePacketsRequest.SetupRequest?)
    /// This request checkpoints the consumer's read progress.
    indirect case commitRequest(CommitRequest?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
