// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SearchConfig stores different properties that will affect search
/// behaviors and search results.
public struct SearchConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name of the search configuration.
  /// For CustomSearchCriteria, search_config would be the search
  /// operator name. For Facets, search_config would be the facet
  /// dimension name.
  /// Format:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/searchConfigs/{search_config}`
  public var name: Swift.String = Swift.String()

  /// Establishes a FacetDimension and associated specifications.
  public var facetProperty: FacetProperty? = nil

  /// Creates a mapping between a custom SearchCriteria and one or more UGA keys.
  public var searchCriteriaProperty: SearchCriteriaProperty? = nil

  /// Initialize a new instance of `SearchConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.SearchConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
