// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Search resource: SearchHypernym.
/// For example,
/// { hypernym: "vehicle"
///   hyponyms: ["sedan", "truck"] }
/// This means in SMART_SEARCH mode, searching for "vehicle" will also return
/// results with "sedan" or "truck" as annotations.
public struct SearchHypernym: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name of the SearchHypernym.
  /// Format:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/searchHypernyms/{search_hypernym}`
  public var name: Swift.String = Swift.String()

  /// Optional. The hypernym.
  public var hypernym: Swift.String = Swift.String()

  /// Optional. Hyponyms that the hypernym is mapped to.
  public var hyponyms: [Swift.String] = []

  /// Initialize a new instance of `SearchHypernym`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchHypernym().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.SearchHypernym"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
