// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for SearchIndexEndpoint.
public struct SearchIndexEndpointRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The index endpoint to search.
  /// Format:
  /// `projects/{project_id}/locations/{location_id}/indexEndpoints/{index_endpoint_id}'
  public var indexEndpoint: Swift.String = Swift.String()

  /// Criteria applied to search results.
  public var criteria: [Criteria] = []

  /// Criteria to exclude from search results.
  /// Note that `fetch_matched_annotations` will be ignored.
  public var exclusionCriteria: [Criteria] = []

  /// Requested page size. API may return fewer results than requested.
  /// If negative, INVALID_ARGUMENT error will be returned.
  /// If unspecified or 0, API will pick a default size, which is 10.
  /// If the requested page size is larger than the maximum size, API will pick
  /// the maximum size, which is 200.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The continuation token to fetch the next page. If empty, it means it is
  /// fetching the first page.
  public var pageToken: Swift.String = Swift.String()

  /// The oneof global search query.
  public var query: OneOf_Query? = nil

  /// Initialize a new instance of `SearchIndexEndpointRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchIndexEndpointRequest().with { $0.imageQuery = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case imageQuery = "imageQuery"
    case textQuery = "textQuery"
    case indexEndpoint = "indexEndpoint"
    case criteria = "criteria"
    case exclusionCriteria = "exclusionCriteria"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.indexEndpoint = try container.decode(Swift.String.self, forKey: .indexEndpoint)
    self.criteria = try container.decode([Criteria].self, forKey: .criteria)
    self.exclusionCriteria = try container.decode([Criteria].self, forKey: .exclusionCriteria)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)

    var query: OneOf_Query? = nil
    let queryCheckAndSet = {
      if query != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'query'"))
      }
      query = $0
    }
    if let imageQuery = try container.decodeIfPresent(ImageQuery?.self, forKey: .imageQuery) {
      try queryCheckAndSet(.imageQuery(imageQuery))
    }
    if let textQuery = try container.decodeIfPresent(Swift.String.self, forKey: .textQuery) {
      try queryCheckAndSet(.textQuery(textQuery))
    }
    self.query = query
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.indexEndpoint, forKey: .indexEndpoint)
    try container.encode(self.criteria, forKey: .criteria)
    try container.encode(self.exclusionCriteria, forKey: .exclusionCriteria)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)

    if let choice = self.query {
      switch choice {
      case .imageQuery(let value):
        try container.encode(value, forKey: .imageQuery)
      case .textQuery(let value):
        try container.encode(value, forKey: .textQuery)
      }
    }
  }

  /// The oneof global search query.
  public enum OneOf_Query: Codable, Equatable, Sendable {
    /// An image-only query.
    indirect case imageQuery(ImageQuery?)
    /// A text-only query.
    case textQuery(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.SearchIndexEndpointRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
