// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Central configuration for custom search criteria.
public struct SearchCriteriaProperty: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Each mapped_field corresponds to a UGA key. To understand how this property
  /// works, take the following example. In the SearchConfig table, the
  /// user adds this entry:
  ///   search_config {
  ///     name: "person"
  ///     search_criteria_property {
  ///       mapped_fields: "player"
  ///       mapped_fields: "coach"
  ///     }
  ///   }
  ///
  /// Now, when a user issues a query like:
  ///   criteria {
  ///     field: "person"
  ///     text_array {
  ///       txt_values: "Tom Brady"
  ///       txt_values: "Bill Belichick"
  ///     }
  ///   }
  ///
  /// MWH search will return search documents where (player=Tom Brady ||
  /// coach=Tom Brady || player=Bill Belichick || coach=Bill Belichick).
  public var mappedFields: [Swift.String] = []

  /// Initialize a new instance of `SearchCriteriaProperty`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchCriteriaProperty().with { $0.mappedFields = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.SearchCriteriaProperty"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
