// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The message that represents server metadata.
public struct ServerMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The offset position for the packet in its stream.
  public var offset: Swift.Int64 = Swift.Int64()

  /// The timestamp at which the stream server receives this packet. This is
  /// based on the local clock of on the server side. It is guaranteed to be
  /// monotonically increasing for the packets within each session; however
  /// this timestamp is not comparable across packets sent to the same stream
  /// different sessions. Session here refers to one individual gRPC streaming
  /// request to the stream server.
  public var ingestTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `ServerMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServerMetadata().with { $0.offset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ServerMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
