// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing the Stream object. The Stream and the Event resources are
/// many to many; i.e., each Stream resource can associate to many Event
/// resources and each Event resource can associate to many Stream resources.
public struct Stream: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of the resource.
  public var name: Swift.String = Swift.String()

  /// Output only. The create timestamp.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update timestamp.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Annotations to allow clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// The display name for the stream resource.
  public var displayName: Swift.String = Swift.String()

  /// Whether to enable the HLS playback service on this stream.
  public var enableHlsPlayback: Swift.Bool = Swift.Bool()

  /// The name of the media warehouse asset for long term storage of stream data.
  /// Format: projects/${p_id}/locations/${l_id}/corpora/${c_id}/assets/${a_id}
  /// Remain empty if the media warehouse storage is not needed for the stream.
  public var mediaWarehouseAsset: Swift.String = Swift.String()

  /// Initialize a new instance of `Stream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Stream().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Stream"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
