// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol StreamsServiceStub: Sendable {
    func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListClustersResponse

    func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Cluster

    func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listStreams(
      request: ListStreamsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListStreamsResponse

    func getStream(
      request: GetStreamRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Stream

    func createStream(
      request: CreateStreamRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateStream(
      request: UpdateStreamRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteStream(
      request: DeleteStreamRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getStreamThumbnail(
      request: GetStreamThumbnailRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateStreamHlsToken(
      request: GenerateStreamHlsTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.GenerateStreamHlsTokenResponse

    func listEvents(
      request: ListEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListEventsResponse

    func getEvent(
      request: GetEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Event

    func createEvent(
      request: CreateEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEvent(
      request: UpdateEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEvent(
      request: DeleteEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listSeries(
      request: ListSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListSeriesResponse

    func getSeries(
      request: GetSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Series

    func createSeries(
      request: CreateSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateSeries(
      request: UpdateSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteSeries(
      request: DeleteSeriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func materializeChannel(
      request: MaterializeChannelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
