// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for UpdateIndexEndpoint.
public struct UpdateIndexEndpointRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource being updated.
  public var indexEndpoint: IndexEndpoint? = nil

  /// Required. Field mask is used to specify the fields to be overwritten in the
  /// IndexEndpoint resource by the update.
  /// The fields specified in the update_mask are relative to the resource, not
  /// the full request.
  /// A field of the resource will be overwritten if it is in the mask.
  /// Empty field mask is not allowed.
  /// If the mask is "*", then this is a full replacement of the resource.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateIndexEndpointRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateIndexEndpointRequest().with { $0.indexEndpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.UpdateIndexEndpointRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
