// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Prediction output format for Video Object Tracking.
public struct VideoObjectTrackingPredictionResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The beginning, inclusive, of the video's time segment in which the
  /// current identifications happens.
  public var segmentStartTime: GoogleCloudWkt.Timestamp? = nil

  /// The end, inclusive, of the video's time segment in which the current
  /// identifications happen. Particularly, if the end is the same as the start,
  /// it means the identifications happen on a specific video frame.
  public var segmentEndTime: GoogleCloudWkt.Timestamp? = nil

  /// All of the objects detected in the specified time range.
  public var objects: [VideoObjectTrackingPredictionResult.DetectedObject] = []

  /// Initialize a new instance of `VideoObjectTrackingPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoObjectTrackingPredictionResult().with { $0.segmentStartTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Boundingbox for detected object. I.e. the rectangle over the video frame
  /// pinpointing the found AnnotationSpec. The coordinates are relative to the
  /// frame size, and the point 0,0 is in the top left of the frame.
  public struct BoundingBox: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The leftmost coordinate of the bounding box.
    public var xMin: Swift.Float = Swift.Float()

    /// The rightmost coordinate of the bounding box.
    public var xMax: Swift.Float = Swift.Float()

    /// The topmost coordinate of the bounding box.
    public var yMin: Swift.Float = Swift.Float()

    /// The bottommost coordinate of the bounding box.
    public var yMax: Swift.Float = Swift.Float()

    /// Initialize a new instance of `BoundingBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BoundingBox().with { $0.xMin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult.BoundingBox"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Each DetectedObject is one particular identification of an object
  /// specified with the AnnotationSpec id and display_name, the bounding box,
  /// the associated confidence score and the corresponding track_id.
  public struct DetectedObject: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The resource ID of the AnnotationSpec that had been identified.
    public var id: Swift.String = Swift.String()

    /// The display name of the AnnotationSpec that had been identified.
    public var displayName: Swift.String = Swift.String()

    /// Boundingbox.
    public var boundingBox: VideoObjectTrackingPredictionResult.BoundingBox? = nil

    /// The Model's confidence in correction of this identification, higher
    /// value means higher confidence.
    public var confidence: Swift.Float = Swift.Float()

    /// The same object may be identified on muitiple frames which are typical
    /// adjacent. The set of frames where a particular object has been detected
    /// form a track. This track_id can be used to trace down all frames for an
    /// detected object.
    public var trackId: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `DetectedObject`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedObject().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult.DetectedObject"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
