// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for ViewIndexedAssets.
public struct ViewIndexedAssetsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The index that owns this collection of assets.
  /// Format:
  /// `projects/{project_number}/locations/{location}/corpora/{corpus}/indexes/{index}`
  public var index: Swift.String = Swift.String()

  /// The maximum number of assets to return. The service may return fewer than
  /// this value.
  /// If unspecified, at most 50 assets will be returned.
  /// The maximum value is 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ViewIndexedAssets` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ViewIndexedAssets` must
  /// match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// The filter applied to the returned list.
  /// Only the following filterings are supported:
  /// "asset_id = xxxx", which returns asset with specified id.
  /// "asset_id = xxxx, yyyy, zzzz", which returns assets with specified ids.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ViewIndexedAssetsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ViewIndexedAssetsRequest().with { $0.index = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ViewIndexedAssetsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
