// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol WarehouseStub: Sendable {
    func createAsset(
      request: CreateAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Asset

    func updateAsset(
      request: UpdateAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Asset

    func getAsset(
      request: GetAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Asset

    func listAssets(
      request: ListAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListAssetsResponse

    func deleteAsset(
      request: DeleteAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func uploadAsset(
      request: UploadAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateRetrievalUrl(
      request: GenerateRetrievalUrlRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.GenerateRetrievalUrlResponse

    func analyzeAsset(
      request: AnalyzeAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func indexAsset(
      request: IndexAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func removeIndexAsset(
      request: RemoveIndexAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func viewIndexedAssets(
      request: ViewIndexedAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ViewIndexedAssetsResponse

    func createIndex(
      request: CreateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateIndex(
      request: UpdateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIndex(
      request: GetIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Index

    func listIndexes(
      request: ListIndexesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListIndexesResponse

    func deleteIndex(
      request: DeleteIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createCorpus(
      request: CreateCorpusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCorpus(
      request: GetCorpusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Corpus

    func updateCorpus(
      request: UpdateCorpusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Corpus

    func listCorpora(
      request: ListCorporaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListCorporaResponse

    func deleteCorpus(
      request: DeleteCorpusRequest, options: GoogleGax.RequestOptions
    ) async throws

    func analyzeCorpus(
      request: AnalyzeCorpusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createDataSchema(
      request: CreateDataSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.DataSchema

    func updateDataSchema(
      request: UpdateDataSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.DataSchema

    func getDataSchema(
      request: GetDataSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.DataSchema

    func deleteDataSchema(
      request: DeleteDataSchemaRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listDataSchemas(
      request: ListDataSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListDataSchemasResponse

    func createAnnotation(
      request: CreateAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Annotation

    func getAnnotation(
      request: GetAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Annotation

    func listAnnotations(
      request: ListAnnotationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListAnnotationsResponse

    func updateAnnotation(
      request: UpdateAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Annotation

    func deleteAnnotation(
      request: DeleteAnnotationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func clipAsset(
      request: ClipAssetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ClipAssetResponse

    func generateHlsUri(
      request: GenerateHlsUriRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.GenerateHlsUriResponse

    func importAssets(
      request: ImportAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createSearchConfig(
      request: CreateSearchConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchConfig

    func updateSearchConfig(
      request: UpdateSearchConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchConfig

    func getSearchConfig(
      request: GetSearchConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchConfig

    func deleteSearchConfig(
      request: DeleteSearchConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listSearchConfigs(
      request: ListSearchConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListSearchConfigsResponse

    func createSearchHypernym(
      request: CreateSearchHypernymRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchHypernym

    func updateSearchHypernym(
      request: UpdateSearchHypernymRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchHypernym

    func getSearchHypernym(
      request: GetSearchHypernymRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchHypernym

    func deleteSearchHypernym(
      request: DeleteSearchHypernymRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listSearchHypernyms(
      request: ListSearchHypernymsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListSearchHypernymsResponse

    func searchAssets(
      request: SearchAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchAssetsResponse

    func searchIndexEndpoint(
      request: SearchIndexEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.SearchIndexEndpointResponse

    func createIndexEndpoint(
      request: CreateIndexEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIndexEndpoint(
      request: GetIndexEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.IndexEndpoint

    func listIndexEndpoints(
      request: ListIndexEndpointsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListIndexEndpointsResponse

    func updateIndexEndpoint(
      request: UpdateIndexEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteIndexEndpoint(
      request: DeleteIndexEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deployIndex(
      request: DeployIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeployIndex(
      request: UndeployIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createCollection(
      request: CreateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCollection(
      request: DeleteCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCollection(
      request: GetCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Collection

    func updateCollection(
      request: UpdateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.Collection

    func listCollections(
      request: ListCollectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ListCollectionsResponse

    func addCollectionItem(
      request: AddCollectionItemRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.AddCollectionItemResponse

    func removeCollectionItem(
      request: RemoveCollectionItemRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.RemoveCollectionItemResponse

    func viewCollectionItems(
      request: ViewCollectionItemsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoAIV1.ViewCollectionItemsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
